### ISSUE TITLE
context / components question

### ISSUE THREAD

**Issue by gardner** [ryanhefner/react-contentful#1]
Hi Ryan,
  thanks for pushing this library. I was just looking at the providor. Did you mean to add `components` to the PropTypes or `context`? Here: https://github.com/ryanhefner/react-contentful/blob/master/src/ContentfulProvider.js#L37

I'm happy to submit PRs if you are open to collaborating. 

Thanks,
  Gardner

**Comment by ryanhefner** [comment]
Hi, @gardner, nice catch! Yeah, `components` was in there by mistake. I was thinking about being able to specify components that are capable of rendering Contentful models based on the `contentType`. But, I'll change that to a `propTypes` declaration for `context` for now until that idea has more time to marinade.

Thanks! And, always down to collaborate 🙌
