### ISSUE TITLE
Version 2.0.3 causes problems in Nextjs

### ISSUE THREAD

**Issue by sanders54** [ryanhefner/react-contentful#112]
Hi.

I use nextjs-contentful react package you also made in cojunction with the Query functions for this. However, this change breaks nextjs building and causes error. See error:

<img width="1188" alt="bilde" src="https://user-images.githubusercontent.com/6704715/73832738-055b5a80-4809-11ea-8e1f-cca8b005016b.png">

**Comment by ryanhefner** [comment]
@sanders54 Thanks, for flagging this quickly. I was doing some React Native development and the default Contentful import was causing issues, but I didn't have a handy `next-contentful` site to test this change in Next.

Just pushed up an update that should resolve it, `2.0.4`, and I’ll continue to look into a solution that plays nice with React Native.

Thanks!
