### ISSUE TITLE
infinite rerendering loop with useContentful

### ISSUE THREAD

**Issue by davidtai** [ryanhefner/react-contentful#125]
useContentful seems to be rerendering indefinitely for me.  I am not sure it is from what I am doing. I am basically using the example from the docs.

It seems like it is being caused by all the set states used internally for setting loading and fetched from the useState hooks.

**Comment by MichaelDM** [comment]
Same issue here.

**Comment by benoj** [comment]
Yep got the same ?

**Comment by itujono** [comment]
No fixes until today? The issue still persists, thou.

**Comment by ryanhefner** [comment]
@itujono Thanks for letting me know. I thought I had pushed up a new version that addresses this issue. Will test and confirm today if that is the case or not.

**Comment by ryanhefner** [comment]
@itujono Should be good now. Let me know if you run into any issues when using `2.0.7`. Thanks!
